name: ga-jfrog-primer-build-1
on: workflow_dispatch
    
permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
jobs:
    ga-jfrog-build-1:
        name: ga-jfrog-build-${{ vars.UNIQUE_ID }}
        runs-on: ubuntu-latest
        env:
          PIP_REMOTE_REPO: ga-jfrog-pip-remote
        steps:
            # Use the specific setup-cli branch
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              id: setup-cli
              env:
                JF_URL: https://${{ vars.JF_URL }}/
                JF_PROJECT: ${{ vars.JF_PROJECT }}
              with:
                  oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}

            - name: Checkout the repository
              uses: actions/checkout@v4
            
            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Configure pip
              run: |
                jf pipc --repo-resolve ${{ env.PIP_REMOTE_REPO }}

            - name: Install Python modules
              # Run 
              run: |
                jf pip install -r requirements.txt

            # Upto this point, nothing is reported to JFrog or GitHub

            # This steps will publish the build info to JFrog
            # and show links in the GitHub Actions summary
            # https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/cli-command-summaries
            # Make sure the project exists in JFrog ^ JF_PROJECT
            - name: Upload files to Artifactory
              run: |
                jf rt u
                
            - name: publish build info
              run: |
                jf rt build-collect-env 
                jf rt build-add-dependencies .
                jf rt build-add-git
                jf rt build-publish
            
            - name: SCA
              run: |
                jf scan

            - name: Trigger build scan
              run: |
                jf rt build-scan
 
            